# Build stage
FROM node:20-alpine as build

WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_WS_URL

ENV VITE_API_URL=$REACT_APP_API_URL
ENV VITE_WS_URL=$REACT_APP_WS_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
